version: '1.0.{build}'

image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python311-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install pyinstaller psycopg2-binary selenium selenium-stealth aiohttp httpx"

build_script:
  - "%PYTHON%\\python.exe -m PyInstaller --onefile --windowed --name ZaloVideoUploader gui_app.py"

artifacts:
  - path: dist\ZaloVideoUploader.exe
    name: ZaloVideoUploader-Windows

deploy: off
